name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-avr avr-libc libelf-dev
      - name: Configure build
        run: |
          mkdir build
          cmake -Bbuild -H.
      - name: Build
        run: cmake --build ./build
